# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(610, 451)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_test_question = QtWidgets.QLabel(self.centralwidget)
        self.label_test_question.setGeometry(QtCore.QRect(10, 70, 591, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_test_question.setFont(font)
        self.label_test_question.setObjectName("label_test_question")
        self.btn_var1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_var1.setGeometry(QtCore.QRect(10, 180, 591, 51))
        self.btn_var1.setObjectName("btn_var1")
        self.btn_var2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_var2.setGeometry(QtCore.QRect(10, 240, 591, 51))
        self.btn_var2.setObjectName("btn_var2")
        self.btn_var3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_var3.setGeometry(QtCore.QRect(10, 300, 591, 51))
        self.btn_var3.setObjectName("btn_var3")
        self.btn_var4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_var4.setGeometry(QtCore.QRect(10, 360, 591, 51))
        self.btn_var4.setObjectName("btn_var4")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.btn_open.setObjectName("btn_open")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(180, 10, 161, 41))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_info.setGeometry(QtCore.QRect(550, 10, 41, 41))
        self.btn_info.setText("")
        self.btn_info.setObjectName("btn_info")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.label_test_question.setText(_translate("main_window", "<html><head/><body><p>Вопрос (номер вопроса и сам вопрос будут отображаться тут)</p></body></html>"))
        self.btn_var1.setText(_translate("main_window", "1. Вариант ответа"))
        self.btn_var2.setText(_translate("main_window", "2. Вариант ответа"))
        self.btn_var3.setText(_translate("main_window", "3. Вариант ответа"))
        self.btn_var4.setText(_translate("main_window", "4. Вариант ответа"))
        self.btn_open.setText(_translate("main_window", "Открыть тест"))
        self.btn_reset.setText(_translate("main_window", "Начать заново"))
        self.btn_info.setToolTip(_translate("main_window", "Справка"))
import ui_res_rc
